FROM amd64/alpine:3.15@sha256:a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9000
ENTRYPOINT ["/usr/bin/prometheus-vcd-sd"]
CMD ["server"]
HEALTHCHECK CMD ["/usr/bin/prometheus-vcd-sd", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/prometheus-vcd-sd /usr/bin/prometheus-vcd-sd
